version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.22.7
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: Report Test Coverage
          command: npm run report-coverage
