version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.15  # April 2022
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: Report Test Coverage
          command: npm run report-coverage
