export default {
  LOCATION: 'ERROR_LOCATION',
  MISSING_CALLBACK: 'ERROR_MISSING_CALLBACK',
  NETWORK: 'ERROR_NETWORK',
  PARAMETERS: 'ERROR_PARAMETERS',
  PERMISSIONS: 'ERROR_PERMISSIONS',
  PUBLISHABLE_KEY: 'ERROR_PUBLISHABLE_KEY',
  RATE_LIMIT: 'ERROR_RATE_LIMIT',
  SERVER: 'ERROR_SERVER',
  UNAUTHORIZED: 'ERROR_UNAUTHORIZED',
};
