export default {
  ERROR_LOCATION: 'ERROR_LOCATION',
  ERROR_NETWORK: 'ERROR_NETWORK',
  ERROR_PERMISSIONS: 'ERROR_PERMISSIONS',
  ERROR_PUBLISHABLE_KEY: 'ERROR_PUBLISHABLE_KEY',
  ERROR_RATE_LIMIT: 'ERROR_RATE_LIMIT',
  ERROR_SERVER: 'ERROR_SERVER',
  ERROR_UNAUTHORIZED: 'ERROR_UNAUTHORIZED',
  SUCCESS: 'SUCCESS',
};
